What's in Your Fruit?
========================================================
## An App for the Nutritionally Curious
author: rdh927
date: Jan 30, 2016


What this app does:
========================================================
1. User selects a fruit as input
2. Compound information is looked up in the database
  + FooDB.ca
3. A data table with compound and health information is returned to the user

```{r, echo=FALSE}
setwd("C:/Users/Rachel/Documents/R Programming/data_prod/")
all_foods <- read.csv("foods.csv")
compounds <- read.csv("compounds.csv")
health_effects <- read.csv("compounds_health_effects.csv")
comp_foods <- read.csv("compounds_foods.csv")
fruits <- subset(all_foods, food_group == "Fruits")

# remove unnecessary cols in prep for merge
fruits2 <- fruits[,1:2]
compounds2 <- compounds[,c(1,2,5)]
comp_foods2 <- comp_foods[,c(2,3,5)]
health_effects2 <- health_effects[,2:5]

#rename some cols to prevent confusion
names(fruits2) <- c("food_id", "food_name")
names(comp_foods2) <- c("compound_id", "food_id", "food_name")
names(compounds2) <- c("compound_id", "legacy_id", "compound_name")
names(health_effects2) <- c("compound_id", "health_effect_id", "health_effect_name", "compound_name")
#do the merge
#merge foods and compounds
foods_comps <- merge(fruits2, comp_foods2, by="food_id")
foods_comps2 <- foods_comps[,1:3]
# merge foods, compounds, and compound names
foods_comps3 <- merge(foods_comps2, compounds2, by="compound_id")
#merge the above with health effects
foods_comps4 <- merge(foods_comps3, health_effects2, by="compound_id")
foods_comps5 <- foods_comps4[,c(1,2,3,5,6,7)]
names(foods_comps5) <- c("compound_id", "food_id", "food_name", "compound_name",
                         "health_effect_id", "health_effect_name")
data <- foods_comps5
data_trunc <- unique(subset(data, food_name == "Kiwi" | food_name =="Pineapple" | food_name == "Custard apple" |
                       food_name == "Star fruit" | food_name == "Papaya" | food_name == "Strawberry" |
                       food_name == "Tamarind"))
print('You entered: Kiwi')
print(head(data_trunc[data_trunc$food_name == 'Kiwi',c(4,6)]),5)
```

Who does it serve?
========================================================
* General public
  + Anyone curious about what they eat
  + Anyone frustrated by unfounded health claims

* Nutritionists
  + Professionals hoping to gain an edge

* Chemists
 + Easily look up natural products for synthesis

Based on facts, not opinions
========================================================
* No need to rely on bloggers
* All info in the database is from peer-reviewed studies
* Stop fearing "chemicals" - they are everywhere and many are beneficial!

> 
## "FooDB is the world’s largest and most comprehensive resource on food constituents, chemistry and biology. It provides information on both macronutrients and micronutrients, including many of the constituents that give foods their flavor, color, taste, texture and aroma."

Conclusion
========================================================
- Intuitive
- Easy to use
- Useful
* No more fearmongering - knowledge is power!
